//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contactos
    {
        public int idContacto { get; set; }
        public string nombresContacto { get; set; }
        public string apellidosContacto { get; set; }
        public string telefonosContacto { get; set; }
        public string correoContacto { get; set; }
        public long numeroIdentificacionContacto { get; set; }
        public Nullable<int> idTipoIdentificacion { get; set; }
    
        public virtual TiposIdentificacion TiposIdentificacion { get; set; }
    }
}
